//go:build !ignore_autogenerated

/*
Copyright 2026 KSquad.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *OTelConfig) DeepCopyInto(out *OTelConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of OTelConfig.
func (in *OTelConfig) DeepCopy() *OTelConfig {
	if in == nil {
		return nil
	}
	out := new(OTelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a runtime.Object deep copy of OTelConfig.
func (in *OTelConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *OTelConfigList) DeepCopyInto(out *OTelConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OTelConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of OTelConfigList.
func (in *OTelConfigList) DeepCopy() *OTelConfigList {
	if in == nil {
		return nil
	}
	out := new(OTelConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a runtime.Object deep copy of OTelConfigList.
func (in *OTelConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *OTelConfigSpec) DeepCopyInto(out *OTelConfigSpec) {
	*out = *in
	in.Exporters.DeepCopyInto(&out.Exporters)
}

// DeepCopy creates a deep copy of OTelConfigSpec.
func (in *OTelConfigSpec) DeepCopy() *OTelConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OTelConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *OTelConfigStatus) DeepCopyInto(out *OTelConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExportedSignals != nil {
		in, out := &in.ExportedSignals, &out.ExportedSignals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of OTelConfigStatus.
func (in *OTelConfigStatus) DeepCopy() *OTelConfigStatus {
	if in == nil {
		return nil
	}
	out := new(OTelConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *OTelExporters) DeepCopyInto(out *OTelExporters) {
	*out = *in
	if in.Traces != nil {
		in, out := &in.Traces, &out.Traces
		*out = new(OTelExporter)
		(*in).DeepCopyInto(*out)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(OTelExporter)
		(*in).DeepCopyInto(*out)
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(OTelExporter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of OTelExporters.
func (in *OTelExporters) DeepCopy() *OTelExporters {
	if in == nil {
		return nil
	}
	out := new(OTelExporters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *OTelExporter) DeepCopyInto(out *OTelExporter) {
	*out = *in
	out.AuthSecretRef = in.AuthSecretRef
	if in.ResourceAttributes != nil {
		in, out := &in.ResourceAttributes, &out.ResourceAttributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Sampling != nil {
		in, out := &in.Sampling, &out.Sampling
		*out = new(SamplingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of OTelExporter.
func (in *OTelExporter) DeepCopy() *OTelExporter {
	if in == nil {
		return nil
	}
	out := new(OTelExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy creates a deep copy of SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SamplingConfig) DeepCopyInto(out *SamplingConfig) {
	*out = *in
	out.Ratio = in.Ratio
}

// DeepCopy creates a deep copy of SamplingConfig.
func (in *SamplingConfig) DeepCopy() *SamplingConfig {
	if in == nil {
		return nil
	}
	out := new(SamplingConfig)
	in.DeepCopyInto(out)
	return out
}
